name: sapsam

channels:
  - conda-forge

dependencies:
  - python=3.11

  # PYTHON AND JUPYTER BASICS
  - pip
  - ipython
  - tqdm
  - joblib
  - jupyterlab

  # DATA SCIENCE BASICS
  - pandas
  - numpy
  - matplotlib
  - seaborn

  # NLP
  - spacy
  - wordcloud
  - stringcase

  # PROJECT INSTALLATION
  - pip:
      - -e .
      - spacy_langdetect
      - language_data
